### ISSUE TITLE
刷新模型列表失败

### ISSUE THREAD

**Issue by AlphatoBeta** [mili-tan/Onllama.Tiny#1]
目前电脑上存在两个模型：①llama2-chinese②svk/docsgpt-7b
使用命令行ollama run svk/docsgpt-7b或者ollama run llama2-chinese都能运行并回答问题。
但是Onllama界面显示：加载模型列列表失败
刷新模型报错：# 刷新模型列表失败：Value cannot be null(Parameter'source')

**Comment by AlphatoBeta** [comment]
log.app内容如下：
time=2024-03-27T14:33:18.145+08:00 level=INFO source=logging.go:45 msg="ollama app started"
time=2024-03-27T14:33:18.163+08:00 level=INFO source=server.go:135 msg="unable to connect to server"
time=2024-03-27T14:33:18.165+08:00 level=INFO source=server.go:91 msg="started ollama server with pid 16860"
time=2024-03-27T14:33:18.165+08:00 level=INFO source=server.go:93 msg="ollama server logs C:\\Users\\lenovo\\AppData\\Local\\Ollama\\server.log"C:\\Users\\lenovo\\AppData\\Local\\Ollama\\server.log"

server.log内容如下：
time=2024-03-27T14:33:18.189+08:00 level=INFO source=images.go:806 msg="total blobs: 7"
time=2024-03-27T14:33:18.195+08:00 level=INFO source=images.go:813 msg="total unused blobs removed: 0"
time=2024-03-27T14:33:18.196+08:00 level=INFO source=routes.go:1110 msg="Listening on 127.0.0.1:11434 (version 0.1.29)"
time=2024-03-27T14:33:18.196+08:00 level=INFO source=payload_common.go:112 msg="Extracting dynamic libraries to C:\\Users\\lenovo\\AppData\\Local\\Temp\\ollama589811916\\runners ..."
time=2024-03-27T14:33:18.227+08:00 level=INFO source=payload_common.go:139 msg="Dynamic LLM libraries [cpu_avx cuda_v11.3 cpu_avx2 cpu rocm_v5.7]"
[GIN] 2024/03/27 - 14:33:18 | 200 |      2.6632ms |       127.0.0.1 | GET      "/api/tags"

**Comment by mili-tan** [comment]
您好，
如果您方便的话，请提供一下您访问 [http://127.0.0.1:11434/api/tags](http://127.0.0.1:11434/api/tags) 返回的内容。

**Comment by mili-tan** [comment]
您好，
已更新 [20240327](https://github.com/mili-tan/Onllama.Tiny/releases/tag/20240327)，请您试试看 20240327 是否解决问题。若未解决请您参考上一个回复提供返回结果。

也谢谢您的反馈！

**Comment by AlphatoBeta** [comment]
经过测试，模型显示一切正常，唯一的遗憾是新版本右下角的设置按钮没有了

**Comment by mili-tan** [comment]
您好，
由于UI库更新布局变化导致了设置按钮消失，已更新 [20240327-1](https://github.com/mili-tan/Onllama.Tiny/releases/tag/20240327-1)。
