### ISSUE TITLE
希望能新增在下載前可顯示模型的大小

### ISSUE THREAD

**Issue by norewolf** [mili-tan/Onllama.Tiny#2]
能否在通過Onllama下載模型之前，顯示模型預計所需的磁盤空間，以確保本地有足夠的空間可以容納？

**Comment by mili-tan** [comment]
你好，实在抱歉 Ollama 似乎暂时没有提供相关 API，也没有提供 Ollama Library 相关的 API。暂时没有办法以结构化的方式获取 Library 中的模型信息，我也在关注和跟进相关的信息。
目前，建议你到 [https://ollama.com/library](https://ollama.com/library/) 手动查询相关信息。

**Comment by mili-tan** [comment]
我测试了一下，registry.ollama.ai 似乎兼容 docker registry v2 api，我也许之后会考虑实现它。
`curl "https://registry.ollama.ai/v2/library/qwen2/manifests/0.5b" -H "Accept: application/vnd.docker.distribution.manifest.v2+json"`
`curl "https://registry.ollama.ai/v2/library/qwen2/tags/list"`

**Comment by mili-tan** [comment]
已支持，https://github.com/mili-tan/Onllama.Tiny/releases/tag/20240630

**Comment by norewolf** [comment]
感x！
________________________________
发件人: Milkey Tan ***@***.***>
发送时间: 2024年6月30日 下午 07:28
收件人: mili-tan/Onllama.Tiny ***@***.***>
抄送: norewolf ***@***.***>; Author ***@***.***>
主题: Re: [mili-tan/Onllama.Tiny] 希望能新增在下d前可@示模型的大小 (Issue #2)


已支持，https://github.com/mili-tan/Onllama.Tiny/releases/tag/20240630

―
